#!/usr/bin/env python3
"""Fallow quality gate for this project.

Exit 0 on pass, 1 on policy failure, 2 on tooling/runtime error.
See docs/fallow/quality-gate.md.

Generated by fallow-kit — edit IN_SCOPE_RE with care.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXCEPTIONS_PATH = ROOT / ".fallow" / "mi-floor-exceptions.json"
MIN_SCORE = 85.0
MI_TARGET = 85.0
MI_FLOOR = 80.0
HIGH_CRAP_RISK = 30.0
HOTSPOT_SCORE_ATTENTION = 40.0
HOTSPOT_CRAP_ATTENTION = 15.0

# Generated by fallow-kit — edit with care
IN_SCOPE_RE = re.compile(
    r"(^\./)"
    r"|(^webpack\.config\.js$)"
    r"|(^cypress/)"
    r"|(^cypress\.config\.js$)"
    r"|(^package\.json$)"
    r"|(^\.fallowrc\.json$)"
    r"|(^scripts/fallow_gate\.py$)"
    r"|(\.jsx?$)"
    r"|(\.tsx?$)",
)


def env_for_fallow() -> dict[str, str]:
    env = os.environ.copy()
    env.setdefault("FALLOW_AGENT_SOURCE", "cursor")
    env.setdefault("FALLOW_SKIP_BINARY_VERIFY", "1")
    return env


def run_fallow(args: list[str]) -> tuple[int, dict | list | None, str]:
    cmd = ["fallow", *args, "--format", "json", "--quiet"]
    try:
        proc = subprocess.run(
            cmd,
            cwd=ROOT,
            env=env_for_fallow(),
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        # Prefer local/npx fallow when global binary is missing (CI).
        cmd = ["npx", "--yes", "fallow", *args, "--format", "json", "--quiet"]
        proc = subprocess.run(
            cmd,
            cwd=ROOT,
            env=env_for_fallow(),
            capture_output=True,
            text=True,
            check=False,
        )

    stdout = (proc.stdout or "").strip()
    stderr = (proc.stderr or "").strip()
    if proc.returncode == 2:
        return 2, None, stderr or stdout or "fallow exited 2"

    payload = None
    if stdout:
        try:
            payload = json.loads(stdout)
        except json.JSONDecodeError as exc:
            return 2, None, f"invalid JSON from fallow {' '.join(args)}: {exc}"

    return proc.returncode, payload, stderr


def is_test_path(path: str) -> bool:
    p = path.replace("\\", "/")
    return (
        "/tests/" in p
        or "/__tests__/" in p
        or p.endswith(
            (
                ".test.js",
                ".test.jsx",
                ".test.ts",
                ".test.tsx",
                ".spec.js",
                ".spec.jsx",
                ".spec.ts",
                ".spec.tsx",
            )
        )
        or p.startswith("cypress/")
    )


def load_mi_exceptions() -> dict[str, str]:
    if not EXCEPTIONS_PATH.exists():
        return {}
    data = json.loads(EXCEPTIONS_PATH.read_text())
    entries = data.get("exceptions") or []
    out: dict[str, str] = {}
    for entry in entries:
        path = entry.get("path")
        reason = (entry.get("reason") or "").strip()
        if path and reason:
            out[path] = reason
    return out


def check_dead_code(failures: list[str]) -> None:
    code, payload, err = run_fallow(["dead-code"])
    if code == 2:
        failures.append(f"dead-code tooling error: {err}")
        return
    if not isinstance(payload, dict):
        failures.append("dead-code: missing JSON payload")
        return
    # Prefer issue counts when present; else non-zero exit means findings.
    summary = payload.get("summary") or {}
    total = summary.get("total_issues")
    if total is None:
        issues = payload.get("issues") or payload.get("findings") or []
        total = len(issues) if isinstance(issues, list) else None
    if code == 1 or (isinstance(total, int) and total > 0):
        failures.append(f"dead-code: {total if total is not None else 'issues found'}")


def check_dupes(failures: list[str]) -> None:
    code, payload, err = run_fallow(["dupes"])
    if code == 2:
        failures.append(f"dupes tooling error: {err}")
        return
    if not isinstance(payload, dict):
        failures.append("dupes: missing JSON payload")
        return
    # Fallow JSON uses top-level clone_groups (+ stats.clone_groups). Exit code
    # stays 0 when clones exist, so the gate must count from the payload.
    # Keep groups/clones + summary.clone_groups as legacy fallbacks.
    groups = (
        payload.get("clone_groups")
        or payload.get("groups")
        or payload.get("clones")
        or []
    )
    stats = payload.get("stats") or {}
    summary = payload.get("summary") or {}
    count = stats.get("clone_groups")
    if count is None:
        count = summary.get("clone_groups")
    if count is None:
        count = len(groups) if isinstance(groups, list) else 0
    try:
        count = int(count)
    except (TypeError, ValueError):
        count = len(groups) if isinstance(groups, list) else 0
    if code == 1 or count > 0:
        failures.append(f"dupes: {count} clone group(s)")


def check_complexity(failures: list[str]) -> None:
    code, payload, err = run_fallow(["health", "--complexity"])
    if code == 2:
        failures.append(f"complexity tooling error: {err}")
        return
    if not isinstance(payload, dict):
        failures.append("complexity: missing JSON payload")
        return
    summary = payload.get("summary") or {}
    above = summary.get("functions_above_threshold", 0)
    findings = payload.get("findings") or []
    # Unit-size over maxUnitSize is reported in large_functions, not findings.
    # Fallow only soft-penalizes unit_size on the score; hard-fail here.
    large = payload.get("large_functions") or []
    large_count = len(large) if isinstance(large, list) else 0
    if code == 1 or above or findings:
        failures.append(
            f"complexity/CRAP: {above or len(findings)} function(s) above threshold"
        )
    if large_count > 0:
        failures.append(f"unit-size: {large_count} function(s) over maxUnitSize")


def check_targets(failures: list[str]) -> None:
    code, payload, err = run_fallow(["health", "--targets"])
    if code == 2:
        failures.append(f"targets tooling error: {err}")
        return
    if not isinstance(payload, dict):
        failures.append("targets: missing JSON payload")
        return
    targets = payload.get("targets")
    if targets is None:
        # Some versions omit targets when empty and only report complexity findings.
        findings = payload.get("findings") or []
        if findings and any(
            (f.get("kind") == "target" or "target" in str(f.get("type", "")).lower())
            for f in findings
            if isinstance(f, dict)
        ):
            failures.append(f"refactoring targets: {len(findings)}")
        return
    if isinstance(targets, list) and targets:
        failures.append(f"refactoring targets: {len(targets)}")


def check_score(failures: list[str]) -> float | None:
    code, payload, err = run_fallow(["health", "--score"])
    if code == 2:
        failures.append(f"score tooling error: {err}")
        return None
    if not isinstance(payload, dict):
        failures.append("score: missing JSON payload")
        return None
    health = payload.get("health_score") or {}
    score = health.get("score")
    if score is None:
        failures.append("score: health_score.score missing")
        return None
    if float(score) < MIN_SCORE:
        failures.append(f"overall health score {score} < {MIN_SCORE}")
    # Also honor fallow's own min-score semantics when exit is 1.
    if code == 1 and float(score) >= MIN_SCORE:
        # Unusual; still surface stderr for visibility.
        if err:
            failures.append(f"score: fallow exit 1 ({err})")
    return float(score)


def check_file_mi_and_hotspots(failures: list[str]) -> None:
    code, payload, err = run_fallow(["health", "--file-scores", "--hotspots"])
    if code == 2:
        failures.append(f"file-scores/hotspots tooling error: {err}")
        return
    if not isinstance(payload, dict):
        failures.append("file-scores/hotspots: missing JSON payload")
        return

    exceptions = load_mi_exceptions()
    file_scores = payload.get("file_scores") or []
    by_path = {f.get("path"): f for f in file_scores if isinstance(f, dict)}

    for path, f in by_path.items():
        if not path or is_test_path(path):
            continue
        mi = f.get("maintainability_index")
        if mi is None:
            continue
        mi = float(mi)
        if mi < MI_FLOOR:
            failures.append(f"MI {mi:.1f} < {MI_FLOOR:.0f}: {path}")
        elif mi < MI_TARGET and path not in exceptions:
            failures.append(
                f"MI {mi:.1f} < {MI_TARGET:.0f} without exception: {path}"
            )

    # Stale exception paths (warn as failure so allowlist stays honest).
    for path in sorted(exceptions):
        if path not in by_path:
            failures.append(f"stale MI exception (file not scored): {path}")
            continue
        mi = by_path[path].get("maintainability_index")
        if mi is not None and float(mi) >= MI_TARGET:
            failures.append(
                f"MI exception obsolete (now {float(mi):.1f} ≥ {MI_TARGET:.0f}): {path}"
            )

    vital = payload.get("vital_signs") or {}
    hotspot_count = vital.get("hotspot_count") or 0
    if hotspot_count:
        failures.append(f"gated hotspot_count={hotspot_count} (must be 0)")

    for path, f in by_path.items():
        if not path or is_test_path(path):
            continue
        crap = f.get("crap_max")
        if crap is not None and float(crap) >= HIGH_CRAP_RISK:
            failures.append(f"high CRAP risk {float(crap):.1f} ≥ {HIGH_CRAP_RISK:.0f}: {path}")

    for h in payload.get("hotspots") or []:
        if not isinstance(h, dict):
            continue
        path = h.get("path") or ""
        score = float(h.get("score") or 0)
        if score < HOTSPOT_SCORE_ATTENTION:
            continue
        fs = by_path.get(path) or {}
        crap = float(fs.get("crap_max") or 0)
        if crap >= HOTSPOT_CRAP_ATTENTION:
            failures.append(
                f"high-risk hotspot score={score:.1f} crap_max={crap:.1f}: {path}"
            )


def path_in_scope(path: str) -> bool:
    p = path.replace("\\", "/").lstrip("./")
    if p.startswith("docs/") and "fallow" not in p:
        return False
    if IN_SCOPE_RE.search(p):
        # Ignore pure markdown/docs except fallow policy already handled.
        if p.endswith((".md", ".mdc")) and not p.startswith(".cursor/"):
            return False
        return True
    return False


def git_in_scope_paths() -> list[str]:
    cmds = [
        ["git", "diff", "--name-only", "HEAD"],
        ["git", "diff", "--name-only", "--cached"],
        ["git", "ls-files", "--others", "--exclude-standard"],
    ]
    paths: set[str] = set()
    for cmd in cmds:
        proc = subprocess.run(
            cmd, cwd=ROOT, capture_output=True, text=True, check=False
        )
        if proc.returncode != 0:
            continue
        for line in (proc.stdout or "").splitlines():
            line = line.strip()
            if line and path_in_scope(line):
                paths.add(line)
    return sorted(paths)


def run_coverage_collection(failures: list[str]) -> None:
    script = ROOT / "scripts" / "collect-coverage.js"
    if not script.exists():
        failures.append("coverage: scripts/collect-coverage.js missing")
        return
    try:
        proc = subprocess.run(
            ["node", str(script)],
            cwd=ROOT,
            env=env_for_fallow(),
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError as exc:
        failures.append(f"coverage tooling error: {exc}")
        return
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout or "").strip()
        failures.append(
            f"coverage collection failed (exit {proc.returncode})"
            + (f": {detail}" if detail else "")
        )


def main(argv: list[str]) -> int:
    check_only = "--check-scope" in argv
    if check_only:
        paths = git_in_scope_paths()
        print(json.dumps({"in_scope": bool(paths), "paths": paths}))
        return 0

    print("fallow-gate: running quality gate…")
    failures: list[str] = []

    run_coverage_collection(failures)
    if failures:
        print("fallow-gate: FAILED")
        for item in failures:
            print(f"  - {item}")
        print("See docs/fallow/quality-gate.md and docs/fallow/remediation.md")
        return 2

    check_dead_code(failures)
    check_dupes(failures)
    check_complexity(failures)
    check_targets(failures)
    score = check_score(failures)
    check_file_mi_and_hotspots(failures)

    if failures:
        print("fallow-gate: FAILED")
        for item in failures:
            print(f"  - {item}")
        print("See docs/fallow/quality-gate.md and docs/fallow/remediation.md")
        return 1

    score_txt = f"{score:.1f}" if score is not None else "n/a"
    print(f"fallow-gate: PASSED (overall score {score_txt})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
